_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "ImageEncoderViT"
  MASK_FORMER:
    FROZE_BACKBONE: False
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  # WEIGHTS: "/home/yguo/Documents/other/segment-anything/sam_vit_h_4b8939.pth"
  # WEIGHTS: "/home/yguo/Documents/other/segment-anything/sam_vit_l_0b3195.pth"
  WEIGHTS: "/home/yguo/Documents/other/segment-anything/sam_vit_b_01ec64.pth"
  # WEIGHTS: "./output_vlm/sam/cs_freeze_90k_sam_vit_huge_180k/model_final.pth"


  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 3
  CHECKPOINT_PERIOD: 180000
TEST:
  EVAL_PERIOD: 20000


DATASETS:
  TRAIN: ("cityscapes_fine_instance_seg_train",) #("cityscapes_fine_instance_seg_train",) #("urbansyn_instance_seg_train",)
  TEST: ("cityscapes_fine_instance_seg_val",)