_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2dinoV2"
  DINOV2:
    PRETRAIN_IMG_SIZE: 512
    PATCH_SIZE: 16
    EMBED_DIM: 1024
    DEPTHS: 24
    NUM_HEADS: 16
    MLP_RATIO: 4
    QKV_BIAS: True
    FFN_BIAS: True
    PROJ_BIAS: True
    INIT_VALUES: 1e-05
    FFN_LAYER: "mlp"
    BLOCK_CHUNKS: 0
  SEM_SEG_HEAD:
    IN_FEATURES: ["res7", "res11", "res15", "res23"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res11", "res15", "res23"]
  WEIGHTS: "/home/yguo/Documents/other/inst_seg_4VFM/pretrain/dinov2_512x512_converted_detectron2.pth" #"./pretrain/dinov2_vitl14_pretrain.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
    FROZE_BACKBONE: True
SOLVER:
  IMS_PER_BATCH: 18
  CHECKPOINT_PERIOD: 5000
  WARMUP_FACTOR: 0.5
  WARMUP_ITERS: 0
  BASE_LR: 0.0001
  MAX_ITER: 15000
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 1024) for x in range(5, 20)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 752
  MAX_SIZE_TRAIN: 2048 # kitti 1408
  MAX_SIZE_TEST: 2816
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE:  (512, 512)  # 1024*1024 will cause shape mismatch in UDA
DATASETS:
  TRAIN: ("urbansyn_instance_seg_train_eval_kitti360",)
  TEST: ("kitti360_instance_seg_val",)
TEST:
  EVAL_PERIOD: 15000
OUTPUT_DIR: "./output/urbansyn_from_scratch"
SAVE_INSTANCE_VISUALIZATION: True
# VIS_PERIOD: 1
