
CUDA_VISIBLE_DEVICES=0 python demo/demo_catogory_fuse.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/category_urbansyn_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/urbansyn_human_cycle/model_final.pth ./output/category/urbansyn_vehicle/model_final.pth' >> visual_instance/category_kitti_all/category_urbansyn_500_on_kitti360_all.txt &
CUDA_VISIBLE_DEVICES=0 python demo/demo_catogory_fuse.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/category_synscapes_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/synscapes_human_cycle/model_final.pth ./output/category/synscapes_vehicle/model_final.pth' >> visual_instance/category_kitti_all/category_synscapes_500_on_kitti360_all.txt &
CUDA_VISIBLE_DEVICES=0 python demo/demo_catogory_fuse.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/category_synthia_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/synthia_human_cycle/model_final.pth ./output/category/synthia_vehicle/model_final.pth' >> visual_instance/category_kitti_all/category_synthia_500_on_kitti360_all.txt &

CUDA_VISIBLE_DEVICES=0 python demo/demo_catogory_single.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/full_urbansyn_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/urbansyn_full/model_final.pth' >> visual_instance/category_kitti_all/full_urbansyn_500_on_kitti360_all.txt &
CUDA_VISIBLE_DEVICES=1 python demo/demo_catogory_single.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/full_synscapes_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/synscapes_full/model_final.pth' >> visual_instance/category_kitti_all/full_synscapes_500_on_kitti360_all.txt &
CUDA_VISIBLE_DEVICES=1 python demo/demo_catogory_single.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/full_synthia_500_on_kitti360_all/ --opts MODEL.WEIGHTS './output/category/synthia_full/model_final.pth' >> visual_instance/category_kitti_all/full_synthia_500_on_kitti360_all.txt &

CUDA_VISIBLE_DEVICES=1 python demo/demo_catogory_single.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/model_90k/ --opts MODEL.WEIGHTS './output/a-kitti/kitti_90k/model_final.pth' >> visual_instance/category_kitti_all/model_90k.txt &
CUDA_VISIBLE_DEVICES=1 python demo/demo_catogory_single.py --input datasets/kitti360/2013_05_28_drive_val_frames_image_all.txt --output visual_instance/category_kitti_all/model_40k/ --opts MODEL.WEIGHTS './output/a-kitti/kitti_40k/model_final.pth' >> visual_instance/category_kitti_all/model_40k.txt 